version: 2
jobs:
  commit-message-check:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout
      - run: python ./.circleci/commit-message-check.py

workflows:
  version: 2
  all:
    jobs:
      - commit-message-check
